[auth]
site_url = "https://k9protrain.com/onboarding"
additional_redirect_urls = [
  "https://k9protrain.com/onboarding",
  "https://k9protrain.com/login",
  "https://k9protrain.com/**",
  "https://www.k9protrain.com/**",
  "https://k9protrain.net/**",
  "https://www.k9protrain.net/**",
  "http://localhost:3000/**"
]
jwt_expiry = 3600
enable_signup = true
enable_anonymous_sign_ins = false

[auth.email]
enable_signup = true
double_confirm_changes = false
enable_confirmations = false
